// src/components/Counter.vue
<template>
  <div class="counter">
    <p>To do: {{ toDo }} {{pluralize(toDo)}}</p>
    <p>Done: {{ done }} {{pluralize(done)}}</p>
  </div>
</template>

<script>
export default {
  name: 'Counter',
  props: ['list'],
  computed: {
    toDo: function () {
      return this.list.filter(item => !item.done).length;
    },
    done: function () {
      return this.list.filter(item => item.done).length;
    }
  },
  methods: {
    pluralize: (length) => {
      return length === 1 ? "item" : "items";
    }
  }
}
</script>

<style scoped>
.counter {
  display: inline-block;
  width: 33%;
  text-align: left;
  font-weight: bold;
}
</style>

// react-todo/src/components/Counter.js
import './Counter.css';

const Counter = ({list}) => {
    const toDo = () => {
        return list.filter(item => !item.done).length;
    };
    const done = () => {
        return list.filter(item => item.done).length;
    };
    const pluralize = (length) => {
        return length === 1 ? "item" : "items";
    }
    
    return (
        <div className="counter">
            <p>To do: { toDo() } { pluralize(toDo()) }</p>
            <p>Done: { done() } { pluralize(done()) }</p>
        </div>
    )
}

export default Counter;
